spring:
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: pass
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver
  sleuth:
    sampler:
      percentage: 1.0